[[main]]
  name = "Talks"
  pageRef = "talks"
  weight = 10

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Interviews"
  pageRef = "interviews"
  weight = 30

[[main]]
  name = "Panels"
  pageRef = "panels"
  weight = 40

[[main]]
  name = "Papers"
  pageRef = "papers"
  weight = 50

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/seantallen"
  weight = 60

[[main]]
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://www.linkedin.com/in/sean-t-allen-has-a-posse/"
  weight = 70

[[main]]
  identifier = "x-twitter"
  pre = "x-twitter"
  url = "https://x.com/seantallen"
  weight = 80

[[main]]
  identifier = "bluesky"
  pre = "bluesky"
  url = "https://bsky.app/profile/seantallen.bsky.social"
  weight = 90

[[main]]
  identifier = "rss"
  pre = "rss"
  url = "/index.xml"
  weight = 100
