baseURL = "https://www.seantallen.com/"
languageCode = "en-us"
title = "www.seantallen.com"
theme = "ananke"
canonifyurls = false

[params]
  custom_css = ["css/my.css"]
  background_color_class = "bg-blue"
  twitter = "https://twitter.com/seantallen"
  github = "https://github.com/seantallen"
  linkedin = "https://www.linkedin.com/in/seantallen/"

[taxonomies]
  tag = "tags"

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "tags"
  weight = 100

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = -110

  [[menu.main]]
    name = "Talks"
    url = "/talks/"
    weight = -100

