baseURL = "https://www.seantallen.com/"
languageCode = "en-us"
title = "www.seantallen.com"
theme = "ananke"
canonifyurls = false
preserveTaxonomyNames = true

[params]
  custom_css = ["css/my.css"]
  background_color_class = "bg-blue"

[taxonomies]
  tag = "tags"

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "tags"
  weight = 100

[menu]
  [[menu.main]]
    name = "talks"
    url = "/talks/"
    weight = -100

