[Settings]
# Added automatically by the Netlify CLI. It has no effect during normal
# Git-backed deploys.
ID = "Your_Site_ID"

# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  base = ""
  publish = "public/"
  command = "hugo"

# Have to set HUGO_VERSION for each environment otherwise we get the 0.17 default
[context.production.environment]
  HUGO_VERSION = "0.56.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.56.0"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.56.0"

[[redirects]]
  from = "https://flamboyant-kepler-ae031d.netlify.com/*"
  to = "https://www.seantallen.com/:splat"
  status = 301
  force = true
