[Settings]
# Added automatically by the Netlify CLI. It has no effect during normal
# Git-backed deploys.
ID = "Your_Site_ID"

# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  base = ""
  publish = "public/"
  command = "bash build.bash"

# Have to set HUGO_VERSION for each environment otherwise we get the 0.17 default
[context.production.environment]
  HUGO_VERSION = "0.56.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.56.0"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.56.0"

[[redirects]]
  from = "https://flamboyant-kepler-ae031d.netlify.com/*"
  to = "https://www.seantallen.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/2018/12/26/things-id-like-in-my-code-management-tool/"
  to = "/posts/code-management-wishlist/"
  status = 301
  force = true

[[redirects]]
  from = "/2016/02/22/learning-from-ada/"
  to = "/posts/learning-from-ada/"
  status = 301
  force = true

[[redirects]]
  from = "/2015/04/19/of-debt-and-decisions/"
  to = "/posts/of-debt-and-decisions/"
  status = 301
  force = true

[[redirects]]
  from = "/2015/04/12/on-becoming-a-better-teacher/"
  to = "/posts/on-becoming-a-better-teacher/"
  status = 301
  force = true

[[redirects]]
  from = "/2015/04/04/storm-applied-behind-the-scenes/"
  to = "/posts/storm-applied/"
  status = 301
  force = true

[[redirects]]
  from = "/2015/02/24/an-acceptable-tool/"
  to = "/posts/an-acceptable-tool/"
  status = 301
  force = true
